import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import { addApplication, addInterview } from '@/lib/db';
import { ApplicationStatus, Priority, InterviewRound, InterviewMode } from '@/types';
import { subDays, format, addDays } from 'date-fns';

export async function POST(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const today = new Date();

    const sampleApplications = [
      {
        company: 'Google',
        role: 'Senior Frontend Engineer',
        status: ApplicationStatus.Interview,
        priority: Priority.High,
        appliedDate: format(subDays(today, 14), 'yyyy-MM-dd'),
        location: 'Mountain View, CA',
        salary: '$180,000',
        source: 'LinkedIn',
      },
      {
        company: 'Meta',
        role: 'Product Engineer',
        status: ApplicationStatus.Rejected,
        priority: Priority.Medium,
        appliedDate: format(subDays(today, 30), 'yyyy-MM-dd'),
        location: 'Menlo Park, CA',
        salary: '$175,000',
        source: 'Referral',
      },
      {
        company: 'Apple',
        role: 'UI Engineer',
        status: ApplicationStatus.Applied,
        priority: Priority.High,
        appliedDate: format(subDays(today, 5), 'yyyy-MM-dd'),
        location: 'Cupertino, CA',
        salary: '$160,000',
        source: 'Company Website',
      },
      {
        company: 'Netflix',
        role: 'Software Engineer (UI)',
        status: ApplicationStatus.Wishlist,
        priority: Priority.Medium,
        appliedDate: format(today, 'yyyy-MM-dd'),
        location: 'Los Gatos, CA',
        salary: '$200,000',
        source: '',
      },
      {
        company: 'Amazon',
        role: 'Frontend Developer',
        status: ApplicationStatus.Offer,
        priority: Priority.Low,
        appliedDate: format(subDays(today, 45), 'yyyy-MM-dd'),
        location: 'Seattle, WA',
        salary: '$150,000',
        source: 'Indeed',
      },
      // Generate 10 more varied ones
      ...Array.from({ length: 10 }).map((_, i) => ({
        company: `TechCorp ${i + 1}`,
        role: 'Software Engineer',
        status: Object.values(ApplicationStatus)[i % 6],
        priority: Object.values(Priority)[i % 4],
        appliedDate: format(subDays(today, i * 3), 'yyyy-MM-dd'),
        location: 'Remote',
        salary: `$${120 + i * 5},000`,
        source: 'AngelList',
      })),
    ];

    for (let i = 0; i < sampleApplications.length; i++) {
      const appData = sampleApplications[i];
      const newApp = await addApplication(supabase, {
        ...appData,
        jdLink: '',
        resumeRef: '',
        notes: 'Sample data generated by seeder.',
        recruiter: '',
        referral: '',
        applicationId: '',
        tags: ['React', 'TypeScript'],
      }, user.id);

      // If status is Interview or Offer, add an interview
      if (appData.status === ApplicationStatus.Interview || appData.status === ApplicationStatus.Offer) {
        await addInterview(supabase, {
          applicationId: newApp.id,
          date: format(addDays(today, (i % 5) + 1), 'yyyy-MM-dd'),
          time: '14:00',
          mode: InterviewMode.Video,
          round: i % 2 === 0 ? InterviewRound.Technical : InterviewRound.HR,
          link: 'https://zoom.us/j/123456789',
          interviewer: 'Jane Doe',
        }, user.id);
      }
    }

    return NextResponse.json({ success: true, message: 'Sample data seeded successfully.' });
  } catch (error) {
    console.error('Error seeding data:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
